### ISSUE TITLE
[11.0]Access error on when creating OU for a non admin user

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/operating-unit#129]
Following up this comment: https://github.com/OCA/operating-unit/issues/94#issuecomment-402386784

I was able to reproduce it on runbot: http://3323845-11-0-eca13e.runbot2.odoo-community.org/web?debug=#menu_id=75&action=86&active_id=channel_inbox

The problem is when the non-admin user creates a OU it is not assigned to the OU recently created so the access error appears. Not sure how to solve this. Maybe assign the user to the OU recently created?

**Comment by gdgellatly** [comment]
Yh I notice it in testing as well.  My solution was `Create as admin user`.  The issue of assigning the user creating it, is often they won't want access to the unit itself.  You don't setup an OU, go back 3 days later as another user setup the next one etc, you typically do them all at once.  I see it as similar to assigning ACL's.

The other alternative is an OU Manager security group with create rights.  But its hard because it involves leaking info everywhere.  Honestly I feel this is one case that Create as Admin is appropriate given the module purpose.

Or else a record rule on create_uid.

**Comment by AaronHForgeFlow** [comment]
@gdgellatly Yes, I agree. Normally, OU are created only once and they are never modified so using the admin user is probably the best solution here. I'll leave this issue opened for a while just in case.

**Comment by meigallodixital** [comment]
As I say in the other thread, the intention here is to simulate physical stores with operational units. So, for us, it would be correct to manage it only as admin. No new stores are created every day: P

My question here, when we talk about admin we talk about the user 'root' not the users within the admin group, right?

Here if we already see a certain problem. That user we have thought not to be used, only to implement before production, since each company (we have multi-company) has its own admins that manage them.

**Comment by AaronHForgeFlow** [comment]
Yes, admin user it's kinda root user.

As @gdgellatly  said, the only alternative is an OU Manager security group with create rights. But that may cause some security issues. Right now the only solution is to log with the admin user here.

**Comment by meigallodixital** [comment]
So, I think the permissions and checkbox in the preferences should be removed from the module, right?

**Comment by AaronHForgeFlow** [comment]
I don't think so. In that case It's not possible to assign a users to multiple operating units.

**Comment by meigallodixital** [comment]
Right, I forgot :)

But I think that the view of creation should only be accessed by 'root', to avoid confusion.

**Comment by AaronHForgeFlow** [comment]
This will be solved soon :rocket:

**Comment by AaronHForgeFlow** [comment]
It is not straightforward https://github.com/OCA/operating-unit/pull/144#discussion_r234954932

**Comment by gdgellatly** [comment]
Workarounds exist, solved in later versions, lets close this
