### ISSUE TITLE
[12.0] Performance issue with res_partner_operating_unit

### ISSUE THREAD

**Issue by max3903** [OCA/operating-unit#258]
After installing and configuring this module, the contacts list is pretty slow (~45 sec with 115 k records).

From Odoo's support comment below, a record rule on a many2many field is not good a idea:

> Many2many fields security rules on big tables are indeed sub-optimal compared to a subselect or join done in SQL directly. This is unfortunate for your case, but this is the expected behaviour of Odoo at this time. Improving this is something we keep in mind for the future, but using joins or more efficient subqueries comes with its own problems, and at the moment we have no real incentive to make this a priority - security rules based on m2m fields are not present in standard modules for a reason; the same way that searching on big tables by followers or by tags could be rather lengthy. It's not really a problem when it's a search - for security rules, since it's added to every query, the impact is indeed more important.

Any idea or suggestion? I want to make sure we are not forgetting a good solution.

Thanks

**Comment by max3903** [comment]
CC: @moylop260

**Comment by moylop260** [comment]
If I understood fine the following line is the performance issue:
 - https://github.com/OCA/operating-unit/blob/040b17de8b1e88cb74d77a9478e8fddccb3d8547/res_partner_operating_unit/security/res_partner_security.xml#L10

I don't know what is the best solution in this moment.
Fast solution in my mind (without thinking too much), maybe, you like to try to make a field in `res.user` to get all valid partner ids for that user (using a faster query directly)

In order to use:
 - ` <field name="domain_force">[('id', 'in', user.partner_allowed_by_ou_ids.ids)]</field>`

Offtopic, You need to clear caches after `partner.operating_unit_ids` field changes, since that [_compute_domain](https://github.com/odoo/odoo/blob/87b127efed97c1f6fad18d6ee6b5924a9b2c70f2/odoo/addons/base/models/ir_rule.py#L71-L77) method has `LRU` cache, but it is a dynamic value, if you don't clear caches so changes in the fields won't be detected.

**Comment by max3903** [comment]
Thanks @moylop260 I think we'll try the other way around (storing the users on the partners) as we have 200+ users and 100+ k partners.

**Comment by max3903** [comment]
Issue persists with both options.

Trying the following option:
* Remove the record rule
* Filter on the OUs in `name_search`

**Comment by IJOL** [comment]
Yeah, almost 3 years later i'm being hit by the very same issue, the "solutions" did not solve anything, this operating_unit_ids=False domain is a performance killer, https://github.com/OCA/operating-unit/blob/94e19bd88c29f91c770b07bc0652b3711ffef80d/res_partner_operating_unit/models/res_partner.py#L39 i've just commented the line, but we need to push a real solution for v12, it seems to me that the issue is resolved in 14.0 by simply having a not null operating_unit_ids and a default for every partner, is that true?
