### ISSUE TITLE
Confusing licesing schema

### ISSUE THREAD

**Issue by antherkiv** [OCA/operating-unit#314]
Hi there, I spent some time looking at the repo and I got confuse, the odoo app store and the __manifest__ tell the modules are LGPV v3 but License file tell the repo is AGPL. So I don't actually understand what license rules over the modules and what are the actual license for each one.

Best Regards

**Comment by luc-demeyer** [comment]
I have the same question. 
In 2018 the License got changed from AGPL to LGPL, cf. https://github.com/OCA/operating-unit/commit/110d6d729169a5badf7cfd32a53ee3a7650c0837

But no explanation in the commit message why this has been done (it says 'improved license terms' but I am sure if AGPL to LGPL is considered as an improvement by everyone).

**Comment by gdgellatly** [comment]
Hi,

Like nearly every other software repo with multiple licenses, the lowest level license for the file or even section of code you are viewing is generally the one that applies, if the code you are looking it is copyrightable. So a module license supersedes a repo license. Just like vendored source licenses will supersede a module one. e.g. this file in odoo https://github.com/odoo/odoo/blob/11.0/odoo/tools/lru.py is partly licensed MIT. 

I think if it is really confusing and matters then the best thing is to seek legal assistance as this pattern is really really commonly seen.

As for the change, @luc-demeyer you are referring to a migration commit, it would be unreasonable to expect full conversations and history. Operating unit modules were LGPL since birth as far as I knew, as they are the kind of module which is hard to make AGPL and best suited to permissive. I imagine the commit was just fixing an oversight where some module incompatibility was introduced.

Closing as not really anything to resolve.
