### ISSUE TITLE
Financial Report `account_financial_report by` Operating Unit

### ISSUE THREAD

**Issue by kittiu** [OCA/operating-unit#369]
Hi,

Is it possible to run financial reports `account_financial_report` by OU?

Note: Like, i.e., mis_builder_operating_unit

Thanks!

**Comment by kittiu** [comment]
@AaronHForgeFlow, do you know?

**Comment by kittiu** [comment]
Hi @AaronHForgeFlow I found your work back in v12, https://github.com/ForgeFlow/account-financial-reporting/tree/12.0-analytic-ou-afr/account_financial_report_operating_unit, not sure what its status.

Is it ok, if I do it again in v14? Do you want to add anything?
Thanks!

**Comment by AaronHForgeFlow** [comment]
Hi @kittiu, I'd be awesome if you migrate that to v14. If I remember correctly, it was working well in v12. I will recheck.

**Comment by AaronHForgeFlow** [comment]
BTW I think it is better to move the module to the operating-unit repo.

**Comment by AaronHForgeFlow** [comment]
Hi again, and sorry for so many messages, That branch  https://github.com/ForgeFlow/account-financial-reporting/tree/12.0-analytic-ou-afr/account_financial_report_operating_unit contains changes in the AFR to filter aged receivables and aged payables by analytic account. The problem is, that is not possible without "hacking" some Odoo core methods. I will remove that part and create a pull request to the operating-unit repo in this case.


Edit: the PR in v12: https://github.com/OCA/operating-unit/pull/372
