### ISSUE TITLE
[14.0] account_operating_unit : error with cash basis

### ISSUE THREAD

**Issue by Saran440** [OCA/operating-unit#424]
Can not register payment when you config `Operating Units are self-balanced on Company` and cash basis
![Selection_004](https://user-images.githubusercontent.com/20896369/139830123-aaff87f9-34cb-465b-8ed1-a4d1e8e96dc5.png)

**Step to error**
1. Configuration
    - Go to menu Settings > Users & Companies > Companies > select `Operating Units are self-balanced` and `Inter-operating unit clearing account`
    ![Selection_005](https://user-images.githubusercontent.com/20896369/139830503-6d3ceea4-1c29-4f21-a79d-f06eef973af7.png)
    - Go to Settings > Invoicing > Check cash basis
    - Create new journal type cash and OU `B2D`
    - Create Undue Tax
2. Create Vendor Bills from OU `B2B` and details is Undue
![Selection_006](https://user-images.githubusercontent.com/20896369/139831162-732353d8-8e2b-4465-b49c-47dfeed87d64.png)

3. Register Payment > select Journal = `B2D` > Create Payment
4. it will error `Configuration error. The operating unit is mandatory for each line as the operating unit has been defined as self-balanced at company level.`

------------

Test with not input undue it's okay.
.

**Comment by hitrosol** [comment]
hi @Saran440, I found other case maybe related to this as well. Since V14, every time we post the bank statement, it will create the journal entry as well. Unfortunately no setting of the OU at the moment, where it's  really need whenever we want to produce the Balance Sheet Report filtered by the OU. 
Maybe by putting the field in the bank statement will help to solve this case.
